### ISSUE TITLE
Bug with setuptools_scm during install with pip

### ISSUE THREAD

**Issue by paugier** [exabl/snek5000#23]
setuptools_scm is really very sensible.

```
pierre@gre ~/Dev/snek5000 master $ pip install -e .                             
Obtaining file:///home/pierre/Dev/snek5000
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  ERROR: Command errored out with exit status 1:
   command: /home/pierre/.pyenv/versions/3.8.2/bin/python3.8 /home/pierre/.pyenv/versions/3.8.2/lib/python3.8/site-packages/pip/_vendor/pep517/_in_process.py get_requires_for_build_wheel /tmp/tmplbof4igl
       cwd: /home/pierre/Dev/snek5000
  Complete output (50 lines):
  /tmp/pip-build-env-4fhq9xco/overlay/lib/python3.8/site-packages/setuptools/dist.py:634: UserWarning: Usage of dash-separated 'project-urls' will not be supported in future versions. Please use the underscore name 'project_urls' instead
    warnings.warn(
  /tmp/pip-build-env-4fhq9xco/overlay/lib/python3.8/site-packages/setuptools/dist.py:634: UserWarning: Usage of dash-separated 'max-line-length' will not be supported in future versions. Please use the underscore name 'max_line_length' instead
    warnings.warn(
  /tmp/pip-build-env-4fhq9xco/overlay/lib/python3.8/site-packages/setuptools_scm/version.py:88: UserWarning: tag 'default/master' no version found
    warnings.warn("tag {!r} no version found".format(tag))
  /tmp/pip-build-env-4fhq9xco/overlay/lib/python3.8/site-packages/setuptools_scm/version.py:88: UserWarning: tag 'default/fix/fluidsim-core-0.4.1' no version found
    warnings.warn("tag {!r} no version found".format(tag))
  Traceback (most recent call last):
    File "/home/pierre/.pyenv/versions/3.8.2/lib/python3.8/site-packages/pip/_vendor/pep517/_in_process.py", line 280, in <module>
      main()
    File "/home/pierre/.pyenv/versions/3.8.2/lib/python3.8/site-packages/pip/_vendor/pep517/_in_process.py", line 263, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
    File "/home/pierre/.pyenv/versions/3.8.2/lib/python3.8/site-packages/pip/_vendor/pep517/_in_process.py", line 114, in get_requires_for_build_wheel
      return hook(config_settings)
    File "/tmp/pip-build-env-4fhq9xco/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 149, in get_requires_for_build_wheel
      return self._get_build_requires(
    File "/tmp/pip-build-env-4fhq9xco/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 130, in _get_build_requires
      self.run_setup()
    File "/tmp/pip-build-env-4fhq9xco/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 145, in run_setup
      exec(compile(code, __file__, 'exec'), locals())
    File "setup.py", line 10, in <module>
      setup()
    File "/tmp/pip-build-env-4fhq9xco/overlay/lib/python3.8/site-packages/setuptools/__init__.py", line 153, in setup
      return distutils.core.setup(**attrs)
    File "/home/pierre/.pyenv/versions/3.8.2/lib/python3.8/distutils/core.py", line 108, in setup
      _setup_distribution = dist = klass(attrs)
    File "/tmp/pip-build-env-4fhq9xco/overlay/lib/python3.8/site-packages/setuptools/dist.py", line 432, in __init__
      _Distribution.__init__(self, {
    File "/home/pierre/.pyenv/versions/3.8.2/lib/python3.8/distutils/dist.py", line 292, in __init__
      self.finalize_options()
    File "/tmp/pip-build-env-4fhq9xco/overlay/lib/python3.8/site-packages/setuptools/dist.py", line 735, in finalize_options
      ep(self)
    File "/tmp/pip-build-env-4fhq9xco/overlay/lib/python3.8/site-packages/setuptools_scm/integration.py", line 61, in infer_version
      dist.metadata.version = _get_version(config)
    File "/tmp/pip-build-env-4fhq9xco/overlay/lib/python3.8/site-packages/setuptools_scm/__init__.py", line 173, in _get_version
      parsed_version = _do_parse(config)
    File "/tmp/pip-build-env-4fhq9xco/overlay/lib/python3.8/site-packages/setuptools_scm/__init__.py", line 127, in _do_parse
      version = _version_from_entrypoints(config) or _version_from_entrypoints(
    File "/tmp/pip-build-env-4fhq9xco/overlay/lib/python3.8/site-packages/setuptools_scm/__init__.py", line 65, in _version_from_entrypoints
      version = _call_entrypoint_fn(root, config, ep.load())
    File "/tmp/pip-build-env-4fhq9xco/overlay/lib/python3.8/site-packages/setuptools_scm/__init__.py", line 46, in _call_entrypoint_fn
      return fn(root, config=config)
    File "/tmp/pip-build-env-4fhq9xco/overlay/lib/python3.8/site-packages/setuptools_scm/hg.py", line 63, in parse
      return _hg_tagdist_normalize_tagcommit(config, tag, dist, node, branch)
    File "/tmp/pip-build-env-4fhq9xco/overlay/lib/python3.8/site-packages/setuptools_scm/hg.py", line 28, in _hg_tagdist_normalize_tagcommit
      return meta(
    File "/tmp/pip-build-env-4fhq9xco/overlay/lib/python3.8/site-packages/setuptools_scm/version.py", line 212, in meta
      assert parsed_version is not None, "Can't parse version %s" % tag
  AssertionError: Can't parse version default/fix/fluidsim-core-0.4.1
  ----------------------------------------
WARNING: Discarding file:///home/pierre/Dev/snek5000. Command errored out with exit status 1: /home/pierre/.pyenv/versions/3.8.2/bin/python3.8 /home/pierre/.pyenv/versions/3.8.2/lib/python3.8/site-packages/pip/_vendor/pep517/_in_process.py get_requires_for_build_wheel /tmp/tmplbof4igl Check the logs for full command output.
ERROR: Command errored out with exit status 1: /home/pierre/.pyenv/versions/3.8.2/bin/python3.8 /home/pierre/.pyenv/versions/3.8.2/lib/python3.8/site-packages/pip/_vendor/pep517/_in_process.py get_requires_for_build_wheel /tmp/tmplbof4igl Check the logs for full command output.
```

**Comment by ashwinvis** [comment]
Indeed you found a nice edge case for setuptools_scm. As a workaround, instead of

```sh
hg clone git://github.com/exabl/snek5000
```

which clones all branches with "problematic names". You can use:

```sh
git clone --recursive https://github.com/exabl/snek5000.git snek5000-git
hg clone snek5000-git/ snek5000/
```

This would ensure only the `master` branch is cloned.

**Comment by ashwinvis** [comment]
I deleted the branches with names containing versions
